#source 'https://rubygems.org'
source 'https://ruby.taobao.org'
gem 'rails', '4.2.4'
gem 'mysql2', "~> 0.3.0"
gem 'bootstrap-sass', '~> 3.3.5'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'bcrypt'
gem 'annotate'
gem 'simple_form'

gem 'will_paginate-bootstrap'
gem 'rename'
gem 'roo'
gem 'axlsx'

gem 'groupdate'
gem 'grape'
gem 'chartkick'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end


